import { useState, useEffect } from 'react';
import mermaid from 'mermaid';

mermaid.initialize({
    startOnLoad: false,
    theme: 'base',
    themeVariables: {
        primaryColor: '#f1f5f9',
        primaryTextColor: '#0f172a',
        primaryBorderColor: '#cbd5e1',
        lineColor: '#334155',
        textColor: '#e2e4eaff',
        edgeLabelBackground: '#ffffff',
        actorTextColor: '#0f172a',
        actorLineColor: '#64748b',
        messageTextColor: '#0f172a',
        noteTextColor: '#0f192fff',
        noteBkgColor: '#fef3c7'
    },
    securityLevel: 'loose',
});

const MermaidDisplay = ({ chart }) => {
    const [svg, setSvg] = useState('');
    const [error, setError] = useState(false);

    useEffect(() => {
        setError(false);
        if (!chart) return;

        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;

        mermaid.parse(chart)
            .then(() => {
                mermaid.render(id, chart).then((result) => {
                    setSvg(result.svg);
                }).catch((e) => {
                    console.error("Mermaid render error:", e);
                    setError(true);
                });
            })
            .catch((e) => {
                console.error("Mermaid syntax error:", e);
                setError(true);
            });
    }, [chart]);

    if (error) {
        return (
            <span className="block bg-red-50 text-red-600 p-4 rounded-lg my-6 border border-red-200 text-sm font-mono overflow-x-auto">
                <p className="font-bold mb-2">⚠️ Invalid Mermaid Syntax Generated by AI:</p>
                <pre>{chart}</pre>
            </span>
        );
    }

    return (
        <span
            className="block my-8 flex justify-center w-full"
            dangerouslySetInnerHTML={{ __html: svg }}
        />
    );
};

export default MermaidDisplay;