import { useState,useEffect } from 'react';
import { Layout, CheckSquare, Hammer, Loader2, Play,Copy,Download,History  } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import mermaid from 'mermaid';
import { planArchitecture, generateArchitecture, evaluateArchitecture ,fetchHistory,fetchDocumentById} from './api';
// import { Layout, CheckSquare, Hammer, Loader2, Play, Copy, Download, } from 'lucide-react';

mermaid.initialize({
    startOnLoad: false,
    theme: 'base', // Switch to base so we can override colors
    themeVariables: {
        // Main shapes
        primaryColor: '#f1f5f9',
        primaryTextColor: '#0f172a',
        primaryBorderColor: '#cbd5e1',

        // Lines and arrows
        lineColor: '#334155',
        textColor: '#e2e4eaff',

        // Specifically fix the text sitting ON the arrows
        edgeLabelBackground: '#ffffff',

        // Sequence diagram specific fixes
        actorTextColor: '#0f172a',
        actorLineColor: '#64748b',
        messageTextColor: '#0f172a',
        noteTextColor: '#0f192fff',
        noteBkgColor: '#fef3c7'
    },
    securityLevel: 'loose',
});

const MermaidDisplay = ({ chart }) => {
    const [svg, setSvg] = useState('');
    const [error, setError] = useState(false);

    useEffect(() => {
        setError(false);
        if (!chart) return;

        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;

        // Use Mermaid's built-in parse function to validate first
        mermaid.parse(chart)
            .then(() => {
                // If parse succeeds, render it
                mermaid.render(id, chart).then((result) => {
                    setSvg(result.svg);
                }).catch((e) => {
                    console.error("Mermaid render error:", e);
                    setError(true);
                });
            })
            .catch((e) => {
                console.error("Mermaid syntax error:", e);
                setError(true);
            });
    }, [chart]);

    if (error) {
        return (
            <span className="block bg-red-50 text-red-600 p-4 rounded-lg my-6 border border-red-200 text-sm font-mono overflow-x-auto">
                <p className="font-bold mb-2">⚠️ Invalid Mermaid Syntax Generated by AI:</p>
                <pre>{chart}</pre>
            </span>
        );
    }

    return <span className="block my-8 flex justify-center w-full" dangerouslySetInnerHTML={{ __html: svg }} />;
};
function App() {
  const [activeTab, setActiveTab] = useState('generator');

  const [prompt, setPrompt] = useState('');
  const [planData, setPlanData] = useState(null);
  const [finalDoc, setFinalDoc] = useState(null);
  const [isPlanning, setIsPlanning] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const [userArchitecture, setUserArchitecture] = useState('');
  const [evalResult, setEvalResult] = useState(null);
  const [isEvaluating, setIsEvaluating] = useState(false);

  const [historyList,setHistoryList]=useState([]);
  const [isLoadingHistory,setIsLoadingHistory]=useState(false);

  useEffect(()=>{
    if(activeTab=='history'){
        loadHistory();
    }
  },[activeTab]);

const loadHistory = async () => {
    setIsLoadingHistory(true);
    try {
      console.log("1. Calling API...");
      const response = await fetchHistory();
      console.log("2. Data from API:", response);

      let safeArray = [];
      if (Array.isArray(response)) {
        safeArray = response;
      } else if (response && Array.isArray(response.data)) {
        safeArray = response.data;
      } else if (response?.data?.history) {
        safeArray = response.data.history;
      }

      console.log("3. Array to set:", safeArray);

      if (safeArray.length === 0) {
         alert("The backend returned data, but the array is empty! Check console.");
      }

      setHistoryList(safeArray);
    } catch (error) {
      console.error("4. ERROR CAUGHT:", error);
      alert("Network Error! The React app could not reach the FastAPI server. Check console for CORS or 404 errors.");
      setHistoryList([]);
    }
    setIsLoadingHistory(false);
  };

  const handleViewPastDocument=async(id, topic)=>{
    setIsLoadingHistory(true);
    try{

        const data=await fetchDocumentById(id);

        setPlanData({system_title:topic,tasks:[]});
        setFinalDoc(data.markdown);
        setActiveTab('generator');
    }catch(error){
        console.error("Failed to load document:",error);
        alert("Could not load the document");

    }
    setIsLoadingHistory(false);
  }

  const handlePlan = async () => {
    if (!prompt) return;

    setIsPlanning(true);
    setPlanData(null);
    setFinalDoc(null);

    try {
      const data = await planArchitecture(prompt);
      setPlanData(data);
    } catch (error) {
      console.error("Planning failed:", error);
      alert("API Error. Check console.");
    }
    setIsPlanning(false);
  };

  const handleApprove = async () => {
    if (!planData?.thread_id) return;
    setIsGenerating(true);

    try {
      const data = await generateArchitecture(planData.thread_id,prompt);
      setFinalDoc(data.markdown);
    } catch (error) {
      console.error("Generation failed:", error);
      alert("API Error. Check console.");
    }
    setIsGenerating(false);
  };

  const handleEvaluate = async () => {
    if (!userArchitecture) return;

    setIsEvaluating(true);
    setEvalResult(null);
    try {
      const data = await evaluateArchitecture(userArchitecture);
      setEvalResult(data);
    } catch (error) {
      console.error("Evaluation failed:", error);
      alert("API Error. Check console");
    }
    setIsEvaluating(false);
  };

  const handleCopy=()=>{
    navigator.clipboard.writeText(finalDoc);
    alert("Markdown copied! Paste this into Google Docs.");


  };

  const handleDownload=()=>{
    const blob=new Blob([finalDoc],{type:'text/markdown'});
    const url=URL.createObjectURL(blob);
    const a =document.createElement('a');
    a.href=url;
    a.download=`${planData?.system_title?.replace(/\s+/g,'_')||'architecture'}.md`;
    a.click();

    URL.revokeObjectURL(url);
  };



  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans selection:bg-blue-500/30">
      {/* Navbar */}
      <nav className="border-b border-slate-800 bg-slate-900 p-4 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2 text-blue-400">
            <Layout size={24} />
            <h1 className="text-xl font-bold tracking-wide">AI Architect</h1>
          </div>
          <div className="flex gap-2 bg-slate-950 p-1 rounded-lg border border-slate-800">
            <button
              onClick={() => setActiveTab('generator')}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'generator' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'text-slate-400 hover:text-slate-200'}`}
            >
              <Hammer size={16} /> System Generator
            </button>

            <button
              onClick={() => setActiveTab('evaluator')}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'evaluator' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'text-slate-400 hover:text-slate-200'}`}
            >
              <CheckSquare size={16} /> RAG Evaluator
            </button>

            {/* --- HISTORY BUTTON ADDED HERE --- */}
            <button
              onClick={() => setActiveTab('history')}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'history' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'text-slate-400 hover:text-slate-200'}`}
            >
              <History size={16} /> History
            </button>
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto p-6 mt-6">
        {/* --- GENERATOR TAB (HITL FLOW) --- */}
        {activeTab === 'generator' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-xl font-semibold mb-2">Design a New System</h2>
              <p className="text-slate-400 text-sm mb-4">Describe the application you want to build. The agents will research and draft a plan.</p>

              <textarea
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-4 text-slate-200 focus:outline-none focus:border-blue-500 transition-colors resize-none h-28"
                placeholder="e.g. A real-time multiplayer chess engine using websockets..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
              <div className="mt-4 flex justify-end">
                <button
                  onClick={handlePlan}
                  disabled={isPlanning || !prompt}
                  className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  {isPlanning ? <Loader2 className="animate-spin" size={18} /> : <Play size={18} />}
                  {isPlanning ? 'Researching & Planning...' : 'Generate Plan'}
                </button>
              </div>
            </div>

            {planData && !finalDoc && (
              <div className="bg-slate-900 border border-indigo-900/50 rounded-xl p-6 shadow-xl animate-in fade-in slide-in-from-bottom-4">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <span className="text-indigo-400 text-xs font-bold uppercase tracking-wider mb-1 block">Review Required</span>
                    <h3 className="text-2xl font-bold">{planData.system_title}</h3>
                  </div>
                  <button
                    onClick={handleApprove}
                    disabled={isGenerating}
                    className="bg-emerald-600 hover:bg-emerald-500 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50 transition-all shadow-lg shadow-emerald-900/20"
                  >
                    {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <CheckSquare size={18} />}
                    {isGenerating ? 'Drafting Document...' : 'Approve & Write Document'}
                  </button>
                </div>

                <h4 className="text-slate-400 font-medium mb-3">Planned Sections:</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {planData.tasks.map((task, i) => (
                    <div key={i} className="bg-slate-950 border border-slate-800 rounded-lg p-3 flex items-start gap-3">
                      <div className="bg-slate-800 text-slate-300 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0">{i + 1}</div>
                    <div>

                      <p className="text-slate-200 text-sm leading-relaxed">{task.title}</p>
                      <p className="text-slate-400 text-xs mt-1">{task.goal}</p>

                    </div>
                    </div>

                  ))}
                </div>
              </div>
            )}
{finalDoc && (
              <div className="mt-12 animate-in fade-in slide-in-from-bottom-4">
                {/* Action Bar */}
                <div className="flex justify-end gap-3 mb-4 max-w-4xl mx-auto">
                  <button onClick={handleCopy} className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg text-sm font-medium transition-colors">
                    <Copy size={16} /> Copy for Google Docs
                  </button>
                  <button onClick={handleDownload} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors shadow-lg shadow-blue-900/20">
                    <Download size={16} /> Download .md
                  </button>
                </div>

                {/* Paper Document Styling */}
            <div className="prose prose-slate prose-blue max-w-none prose-headings:font-bold prose-h1:text-4xl prose-h2:text-2xl prose-h2:border-b prose-h2:pb-2 prose-h2:mt-10">
                    <ReactMarkdown
                      components={{
                        code(props) {
                          const { children, className, node, ...rest } = props;
                          const match = /language-(\w+)/.exec(className || '');

                          // 1. Render Mermaid diagrams
                          if (match && match[1] === 'mermaid') {
                            return <MermaidDisplay chart={String(children).replace(/\n$/, '')} />;
                          }

                          // 2. Render standard dark-mode code blocks for actual code (JSON, YAML, etc.)
                          if (match) {
                            return (
                              <code className="block bg-slate-900 text-slate-300 rounded-lg p-4 my-6 overflow-x-auto text-sm font-mono shadow-inner not-prose" {...rest}>
                                {children}
                              </code>
                            );
                          }

                          // 3. Render inline code highlighting (e.g. `const x = 5`)
                          return (
                            <code className="bg-slate-100 text-pink-600 px-1.5 py-0.5 rounded text-sm font-mono border border-slate-200" {...rest}>
                              {children}
                            </code>
                          );
                        }
                      }}
                    >
                      {finalDoc}
                    </ReactMarkdown>
                  </div>
                </div>

            )}
            </div>
        )}
        {/* <-- MISSING DIV CLOSURE ADDED HERE */}

        {/* --- EVALUATOR TAB (RAG) --- */}
        {activeTab === 'evaluator' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-xl font-semibold mb-2">Architecture Evaluator (RAG)</h2>
              <p className="text-slate-400 text-sm mb-4">Paste your system architecture here. The AI will cross-reference it against Neon DB best practices.</p>

              <textarea
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-4 text-slate-200 focus:outline-none focus:border-blue-500 transition-colors resize-none h-40 font-mono text-sm"
                placeholder="e.g. I am using a monolithic Node server with local PostgreSQL and no Redis cache..."
                value={userArchitecture}
                onChange={(e) => setUserArchitecture(e.target.value)}
              />
              <div className="mt-4 flex justify-end">
                <button
                  onClick={handleEvaluate}
                  disabled={isEvaluating || !userArchitecture}
                  className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  {isEvaluating ? <Loader2 className="animate-spin" size={18} /> : <Play size={18} />}
                  {isEvaluating ? 'Evaluating Vector DB...' : 'Evaluate System'}
                </button>
              </div>
            </div>

            {evalResult && (
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 shadow-xl animate-in fade-in">
                <div className="mb-6 inline-flex items-center gap-2 bg-slate-950 border border-slate-800 px-4 py-2 rounded-full">
                  <span className="text-slate-400 text-sm">Neon DB Rules Matched:</span>
                  <span className="text-blue-400 font-bold">{evalResult.matched_rules_count}</span>
                </div>
                <div className="prose prose-invert max-w-none prose-headings:text-blue-400">
                  <ReactMarkdown>{evalResult.evaluation_scorecard}</ReactMarkdown>
                </div>
              </div>
            )}
          </div>
        )}

   {/* --- HISTORY TAB --- */}
    {/* --- HISTORY TAB --- */}
        {activeTab === 'history' && (
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl animate-in fade-in">
            <h2 className="text-xl font-semibold mb-6 flex items-center gap-2">
              <History size={20} className="text-blue-400" />
              Past Architectures ({Array.isArray(historyList) ? historyList.length : 'Not an array'})
            </h2>

            {isLoadingHistory ? (
              <div className="flex flex-col items-center justify-center py-12 text-slate-400">
                <Loader2 className="animate-spin mb-2" size={24} />
                <p>Loading database records...</p>
              </div>
            ) : Array.isArray(historyList) && historyList.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {historyList.map((doc, index) => (
                  <div
                    key={doc?.id || index}
                    onClick={() => handleViewPastDocument(doc?.id, doc?.topic)}
                    className="bg-slate-950 border border-slate-800 hover:border-blue-500/50 p-4 rounded-lg cursor-pointer transition-all hover:shadow-lg hover:shadow-blue-900/10 group flex items-start gap-3"
                  >
                    <div className="bg-slate-800 text-blue-400 p-2 rounded-md group-hover:bg-blue-600 group-hover:text-white transition-colors">
                      <Layout size={18} />
                    </div>
                    <div>
                      <h3 className="text-slate-200 font-medium line-clamp-2 text-sm leading-snug">{doc?.topic || "Unknown Topic"}</h3>
                      <p className="text-slate-500 text-xs mt-1">ID: #{doc?.id || "N/A"}</p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-12 text-slate-500 overflow-x-auto">
                <History size={48} className="mx-auto mb-3 opacity-20" />
                <p>No architectures saved yet (or data format error).</p>
                <div className="mt-4 p-4 bg-slate-950 rounded text-left text-xs font-mono text-red-400 max-w-full">
                  <strong>Debug info - type of historyList:</strong> {typeof historyList}
                  <br />
                  <strong>Raw value:</strong> {JSON.stringify(historyList, null, 2)}
                </div>
              </div>
            )}
          </div>
        )}

      </main>
          </div>

  );
}

export default App;